import type { Locale } from '@/domain/types';

export const copy = {
  en: {
    cycle: 'Cycle', history: 'History', settings: 'Settings', title: 'Your cycle', private: 'Private by default. Yours alone.', estimated: 'Period estimated', varies: 'Estimates can vary', logToday: 'Log today', basedOn: (n: number) => n ? `Based on ${n} recent cycles` : 'Based on your starting estimate', cycleDay: (n: number) => `Cycle day ${n}`,
    logged: 'Logged period', estimate: 'Estimated period', recentPattern: 'Your recent pattern', avgCycle: 'Average cycle', avgPeriod: 'Average period', days: 'days', insufficient: 'Keep logging to see descriptive patterns. We never infer causes or conditions.', recentCycles: 'Recent cycles',
    privacySettings: 'Privacy & preferences', settingsLead: 'No account. No ads. Nothing leaves this device.', language: 'Language', appearance: 'Appearance', appearanceDetail: 'Match this device or choose a theme', systemTheme: 'System', lightTheme: 'Light', darkTheme: 'Dark', reminders: 'Discreet reminders', appLock: 'App lock', export: 'Export my data', exportWarning: 'Exports are plaintext after they leave the app. Share them only with someone you trust.', pdf: 'Share PDF', csv: 'Share CSV', delete: 'Delete all data', deleteBody: 'This removes all logs, reminders, settings, and temporary exports from this device. It cannot be undone.', cancel: 'Cancel', confirmDelete: 'Delete everything', privacyPolicy: 'Privacy policy', notMedical: 'This app is not a medical device. Seek professional care for medical advice, diagnosis, or treatment.',
    daily: 'Daily check-in', optional: 'Everything is optional.', flow: 'Flow', pain: 'Pain', mood: 'Mood', energy: 'Energy', symptoms: 'Symptoms', notes: 'Private note', save: 'Save log', spotting: 'Spotting', bloating: 'Bloating', headache: 'Headache', cramps: 'Cramps', none: 'None', light: 'Light', medium: 'Medium', heavy: 'Heavy', veryHeavy: 'Very heavy', low: 'Low', okay: 'Okay', good: 'Good', high: 'High', saved: 'Saved',
    welcome: 'A calmer way to know your cycle', welcomeBody: 'Track periods and symptoms without an account, ads, or fertility claims.', ageTitle: 'Your privacy comes first', ageBody: 'This app is for people aged 13 and older. It does not diagnose or treat conditions.', ageConfirm: 'I am 13 or older', setupTitle: 'Tell us your usual pattern', cycleLength: 'Typical cycle length', periodLength: 'Typical period length', continue: 'Continue', start: 'Start tracking', unlock: 'Unlock', retry: 'Try again',
  },
  tr: {
    cycle: 'Döngü', history: 'Geçmiş', settings: 'Ayarlar', title: 'Döngün', private: 'Varsayılan olarak gizli. Yalnızca senin.', estimated: 'Tahmini adet', varies: 'Tahminler değişebilir', logToday: 'Bugünü kaydet', basedOn: (n: number) => n ? `Son ${n} döngüne göre` : 'Başlangıç tahminine göre', cycleDay: (n: number) => `Döngünün ${n}. günü`,
    logged: 'Kayıtlı adet', estimate: 'Tahmini adet', recentPattern: 'Son düzenin', avgCycle: 'Ortalama döngü', avgPeriod: 'Ortalama adet', days: 'gün', insufficient: 'Açıklayıcı örüntüler için kayıt yapmaya devam et. Neden veya durum çıkarsaması yapmayız.', recentCycles: 'Son döngüler',
    privacySettings: 'Gizlilik ve tercihler', settingsLead: 'Hesap yok. Reklam yok. Hiçbir veri cihazından çıkmaz.', language: 'Dil', appearance: 'Görünüm', appearanceDetail: 'Cihazı takip et veya bir tema seç', systemTheme: 'Sistem', lightTheme: 'Açık', darkTheme: 'Koyu', reminders: 'Gizli hatırlatmalar', appLock: 'Uygulama kilidi', export: 'Verilerimi dışa aktar', exportWarning: 'Dışa aktarılan dosyalar uygulamadan çıktıktan sonra şifrelenmez. Yalnızca güvendiğin kişilerle paylaş.', pdf: 'PDF paylaş', csv: 'CSV paylaş', delete: 'Tüm verileri sil', deleteBody: 'Bu işlem kayıtları, hatırlatmaları, ayarları ve geçici dosyaları bu cihazdan kaldırır. Geri alınamaz.', cancel: 'Vazgeç', confirmDelete: 'Her şeyi sil', privacyPolicy: 'Gizlilik politikası', notMedical: 'Bu uygulama tıbbi cihaz değildir. Tıbbi tavsiye, tanı veya tedavi için bir sağlık uzmanına danış.',
    daily: 'Günlük takip', optional: 'Her alan isteğe bağlıdır.', flow: 'Akış', pain: 'Ağrı', mood: 'Ruh hali', energy: 'Enerji', symptoms: 'Belirtiler', notes: 'Özel not', save: 'Kaydı kaydet', spotting: 'Lekelenme', bloating: 'Şişkinlik', headache: 'Baş ağrısı', cramps: 'Kramplar', none: 'Yok', light: 'Hafif', medium: 'Orta', heavy: 'Yoğun', veryHeavy: 'Çok yoğun', low: 'Düşük', okay: 'İyi', good: 'Güzel', high: 'Yüksek', saved: 'Kaydedildi',
    welcome: 'Döngünü anlamanın daha sakin yolu', welcomeBody: 'Hesap, reklam veya doğurganlık iddiası olmadan adet ve belirtilerini takip et.', ageTitle: 'Gizliliğin her şeyden önce gelir', ageBody: 'Bu uygulama 13 yaş ve üzeri kişiler içindir. Tanı veya tedavi sunmaz.', ageConfirm: '13 yaşında veya daha büyüğüm', setupTitle: 'Genel düzenini paylaş', cycleLength: 'Genel döngü süresi', periodLength: 'Genel adet süresi', continue: 'Devam et', start: 'Takibe başla', unlock: 'Kilidi aç', retry: 'Tekrar dene',
  },
} as const;

export function useCopy(locale: Locale) { return copy[locale]; }
