import { useMemo, useState } from 'react';
import { Image, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { AppPalette } from '@/constants/palette';
import { copy } from '@/i18n/copy';
import { useApp } from '@/state/AppContext';
import { useTheme } from '@/state/ThemeContext';

function Stepper({ label, value, min, max, onChange, unit }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void; unit: string }) { const { colors } = useTheme(); const styles = useMemo(() => createStyles(colors), [colors]); return <View style={styles.stepper}><View style={{ flex: 1 }}><Text style={styles.stepperLabel}>{label}</Text><Text style={styles.stepperDetail}>{value} {unit}</Text></View><Pressable accessibilityLabel={`Decrease ${label}`} onPress={() => onChange(Math.max(min, value - 1))} style={styles.stepButton}><Text style={styles.stepSymbol}>−</Text></Pressable><Text style={styles.stepValue}>{value}</Text><Pressable accessibilityLabel={`Increase ${label}`} onPress={() => onChange(Math.min(max, value + 1))} style={styles.stepButton}><Text style={styles.stepSymbol}>+</Text></Pressable></View>; }

export default function OnboardingScreen() {
  const app = useApp(); const [locale, setLocale] = useState(app.settings.locale); const t = copy[locale]; const [step, setStep] = useState(0); const [age, setAge] = useState(false); const [cycle, setCycle] = useState(app.settings.baselineCycleLength); const [period, setPeriod] = useState(app.settings.baselinePeriodLength);
  const { colors } = useTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  const finish = () => app.replaceSettings({ ...app.settings, locale, baselineCycleLength: cycle, baselinePeriodLength: period, onboardingComplete: true });
  return <SafeAreaView style={styles.root}><Image source={require('@/assets/app/eucalyptus-branch.png')} style={styles.botanical} /><View style={styles.progress}><View style={styles.progressActive} /><View style={step >= 1 ? styles.progressActive : styles.progressInactive} /><View style={step >= 2 ? styles.progressActive : styles.progressInactive} /></View>
    {step === 0 ? <View style={styles.center}><View style={styles.language}><Pressable onPress={() => setLocale('en')} style={[styles.langButton, locale === 'en' && styles.langActive]}><Text style={[styles.langText, locale === 'en' && styles.langTextActive]}>EN</Text></Pressable><Pressable onPress={() => setLocale('tr')} style={[styles.langButton, locale === 'tr' && styles.langActive]}><Text style={[styles.langText, locale === 'tr' && styles.langTextActive]}>TR</Text></Pressable></View><Ionicons name="shield-checkmark" size={44} color={colors.forest} /><Text style={styles.title}>{t.welcome}</Text><Text style={styles.body}>{t.welcomeBody}</Text><Pressable style={styles.primary} onPress={() => setStep(1)}><Text style={styles.primaryText}>{t.continue}</Text></Pressable></View> : null}
    {step === 1 ? <View style={styles.center}><Ionicons name="lock-closed" size={44} color={colors.forest} /><Text style={styles.title}>{t.ageTitle}</Text><Text style={styles.body}>{t.ageBody}</Text><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: age }} onPress={() => setAge((value) => !value)} style={[styles.age, age && styles.ageActive]}><View style={[styles.checkbox, age && styles.checkboxActive]}>{age ? <Ionicons name="checkmark" size={17} color={colors.onPrimary} /> : null}</View><Text style={styles.ageText}>{t.ageConfirm}</Text></Pressable><Pressable disabled={!age} style={[styles.primary, !age && styles.disabled]} onPress={() => setStep(2)}><Text style={styles.primaryText}>{t.continue}</Text></Pressable></View> : null}
    {step === 2 ? <View style={styles.center}><Ionicons name="calendar" size={44} color={colors.forest} /><Text style={styles.title}>{t.setupTitle}</Text><Text style={styles.body}>{locale === 'tr' ? 'Bunu istediğin zaman değiştirebilirsin. Tahminler kayıt yaptıkça uyum sağlar.' : 'You can change this anytime. Estimates adapt as you log.'}</Text><Stepper label={t.cycleLength} value={cycle} min={21} max={45} onChange={setCycle} unit={t.days} /><Stepper label={t.periodLength} value={period} min={2} max={10} onChange={setPeriod} unit={t.days} /><Pressable style={styles.primary} onPress={finish}><Text style={styles.primaryText}>{t.start}</Text></Pressable></View> : null}
  </SafeAreaView>;
}

const createStyles = (colors: AppPalette) => StyleSheet.create({ root: { flex: 1, overflow: 'hidden', backgroundColor: colors.cream }, botanical: { position: 'absolute', top: -45, right: -90, width: 300, height: 330, opacity: .25, resizeMode: 'contain' }, progress: { flexDirection: 'row', gap: 6, marginTop: 22, marginHorizontal: 28 }, progressActive: { width: 30, height: 4, borderRadius: 2, backgroundColor: colors.primary }, progressInactive: { width: 30, height: 4, borderRadius: 2, backgroundColor: colors.line }, center: { flex: 1, justifyContent: 'center', paddingHorizontal: 28, paddingBottom: 35 }, language: { position: 'absolute', top: 28, right: 28, flexDirection: 'row', padding: 3, borderRadius: 12, backgroundColor: colors.sageSoft }, langButton: { width: 40, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 9 }, langActive: { backgroundColor: colors.primary }, langText: { color: colors.muted, fontSize: 11, fontWeight: '700' }, langTextActive: { color: colors.onPrimary }, title: { maxWidth: 330, marginTop: 24, color: colors.forestDark, fontFamily: 'serif', fontSize: 37, lineHeight: 43, fontWeight: '700' }, body: { maxWidth: 330, marginTop: 15, marginBottom: 25, color: colors.muted, fontSize: 15, lineHeight: 23 }, primary: { minHeight: 55, alignItems: 'center', justifyContent: 'center', marginTop: 18, borderRadius: 18, backgroundColor: colors.primary }, disabled: { opacity: .4 }, primaryText: { color: colors.onPrimary, fontSize: 16, fontWeight: '700' }, age: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 13, paddingHorizontal: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 18, backgroundColor: colors.paper }, ageActive: { borderColor: colors.forest, backgroundColor: colors.sageSoft }, checkbox: { width: 27, height: 27, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: colors.sage, borderRadius: 8 }, checkboxActive: { borderColor: colors.primary, backgroundColor: colors.primary }, ageText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '600' }, stepper: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, stepperLabel: { color: colors.ink, fontSize: 14, fontWeight: '700' }, stepperDetail: { marginTop: 4, color: colors.muted, fontSize: 11 }, stepButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.sage, borderRadius: 12, backgroundColor: colors.paper }, stepSymbol: { color: colors.forest, fontSize: 22 }, stepValue: { width: 38, color: colors.forestDark, fontSize: 16, fontWeight: '700', textAlign: 'center' } });
