import { useMemo } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import type { AppPalette } from '@/constants/palette';
import type { ThemePreference } from '@/domain/types';
import { copy } from '@/i18n/copy';
import { exportService } from '@/services/ExportService';
import { reminderScheduler } from '@/services/ReminderScheduler';
import { useApp } from '@/state/AppContext';
import { useTheme } from '@/state/ThemeContext';

function SettingRow({ icon, title, detail, action }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail?: string; action: React.ReactNode }) { const { colors } = useTheme(); const styles = useMemo(() => createStyles(colors), [colors]); return <View style={styles.row}><View style={styles.icon}><Ionicons name={icon} size={21} color={colors.forest} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{title}</Text>{detail ? <Text style={styles.rowDetail}>{detail}</Text> : null}</View>{action}</View>; }

export default function SettingsScreen() {
  const app = useApp(); const { settings, events, logs, estimate } = app; const t = copy[settings.locale]; const router = useRouter();
  const { colors } = useTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  const insets = useSafeAreaInsets();
  const setReminders = async (enabled: boolean) => { const next = { ...settings, reminders: { ...settings.reminders, enabled } }; const scheduled = await reminderScheduler.reschedule(next, estimate); await app.replaceSettings({ ...next, reminders: { ...next.reminders, enabled: enabled && scheduled } }); if (enabled && !scheduled) Alert.alert(t.reminders, settings.locale === 'tr' ? 'Bildirim izni verilmedi.' : 'Notification permission was not granted.'); };
  const openExport = () => Alert.alert(t.export, t.exportWarning, [{ text: t.cancel, style: 'cancel' }, { text: t.pdf, onPress: () => exportService.sharePdf(events, logs, settings.locale) }, { text: t.csv, onPress: () => exportService.shareCsv(logs) }]);
  const remove = () => Alert.alert(t.delete, t.deleteBody, [{ text: t.cancel, style: 'cancel' }, { text: t.confirmDelete, style: 'destructive', onPress: app.deleteAllData }]);
  return <ScrollView style={styles.root} contentContainerStyle={[styles.content, { paddingTop: insets.top + 20 }]}><Text style={styles.kicker}>{t.private.toUpperCase()}</Text><Text style={styles.title}>{t.privacySettings}</Text><Text style={styles.lead}>{t.settingsLead}</Text>
    <View style={styles.group}><SettingRow icon="language" title={t.language} detail="English · Türkçe" action={<View style={styles.segment}><Pressable accessibilityLabel="English" onPress={() => app.updateSettings({ locale: 'en' })} style={[styles.segmentButton, settings.locale === 'en' && styles.segmentActive]}><Text style={[styles.segmentText, settings.locale === 'en' && styles.segmentTextActive]}>EN</Text></Pressable><Pressable accessibilityLabel="Türkçe" onPress={() => app.updateSettings({ locale: 'tr' })} style={[styles.segmentButton, settings.locale === 'tr' && styles.segmentActive]}><Text style={[styles.segmentText, settings.locale === 'tr' && styles.segmentTextActive]}>TR</Text></Pressable></View>} /><SettingRow icon={settings.theme === 'dark' ? 'moon' : settings.theme === 'light' ? 'sunny' : 'phone-portrait-outline'} title={t.appearance} detail={t.appearanceDetail} action={<View style={styles.segment}>{(['system', 'light', 'dark'] as ThemePreference[]).map((option) => { const label = option === 'system' ? t.systemTheme : option === 'light' ? t.lightTheme : t.darkTheme; return <Pressable accessibilityLabel={label} accessibilityState={{ selected: settings.theme === option }} key={option} onPress={() => app.updateSettings({ theme: option })} style={[styles.themeButton, settings.theme === option && styles.segmentActive]}><Ionicons name={option === 'system' ? 'phone-portrait-outline' : option === 'light' ? 'sunny-outline' : 'moon-outline'} size={15} color={settings.theme === option ? colors.onPrimary : colors.muted} /></Pressable>; })}</View>} /><SettingRow icon="notifications-outline" title={t.reminders} detail={settings.locale === 'tr' ? 'Sessiz, yalnızca cihazında' : 'Silent and only on this device'} action={<Switch value={settings.reminders.enabled} onValueChange={setReminders} trackColor={{ true: colors.primary }} />} /><SettingRow icon="lock-closed-outline" title={t.appLock} detail={settings.locale === 'tr' ? 'Biyometri veya cihaz şifresi' : 'Biometrics or device passcode'} action={<Switch value={settings.lockEnabled} onValueChange={(lockEnabled) => app.updateSettings({ lockEnabled })} trackColor={{ true: colors.primary }} />} /></View>
    <View style={styles.group}><Pressable accessibilityRole="button" onPress={openExport}><SettingRow icon="share-outline" title={t.export} detail="PDF · CSV" action={<Ionicons name="chevron-forward" size={19} color={colors.muted} />} /></Pressable><Pressable accessibilityRole="button" onPress={() => router.push('/privacy')}><SettingRow icon="shield-checkmark-outline" title={t.privacyPolicy} detail={t.private} action={<Ionicons name="chevron-forward" size={19} color={colors.muted} />} /></Pressable></View>
    <Pressable accessibilityRole="button" onPress={remove} style={styles.delete}><Ionicons name="trash-outline" size={19} color={colors.danger} /><Text style={styles.deleteText}>{t.delete}</Text></Pressable><Text style={styles.disclaimer}>{t.notMedical}</Text>
  </ScrollView>;
}

const createStyles = (colors: AppPalette) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.cream }, content: { paddingTop: 64, paddingHorizontal: 20, paddingBottom: 40 }, kicker: { color: colors.moss, fontSize: 10, fontWeight: '700', letterSpacing: .7 }, title: { marginTop: 7, color: colors.forestDark, fontFamily: 'serif', fontSize: 32, fontWeight: '700' }, lead: { marginTop: 9, marginBottom: 24, color: colors.muted, fontSize: 13, lineHeight: 19 }, group: { marginBottom: 15, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 22, backgroundColor: colors.paper }, row: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, icon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: colors.sageSoft }, rowCopy: { flex: 1 }, rowTitle: { color: colors.ink, fontSize: 14, fontWeight: '700' }, rowDetail: { marginTop: 3, color: colors.muted, fontSize: 10 }, segment: { flexDirection: 'row', padding: 3, borderRadius: 11, backgroundColor: colors.sageSoft }, segmentButton: { minWidth: 36, minHeight: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 8 }, themeButton: { width: 31, minHeight: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 8 }, segmentActive: { backgroundColor: colors.primary }, segmentText: { color: colors.muted, fontSize: 10, fontWeight: '700' }, segmentTextActive: { color: colors.onPrimary }, delete: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, deleteText: { color: colors.danger, fontSize: 13, fontWeight: '700' }, disclaimer: { marginTop: 12, color: colors.muted, fontSize: 10, lineHeight: 15, textAlign: 'center' } });
